apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-server
  name: cassandra-server-svc
spec:
  clusterIP: None
  ports:
    - port: 7000
      name: intra-node
    - port: 7001
      name: tls-intra-node
    - port: 7199
      name: jmx
    - port: 9042
      name: cql
    - port: 9160
      name: thrift
  selector:
    app: cassandra-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-server
  labels:
    app: cassandra-server
    can_serve: "true"
    is_workload: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-server
      can_serve: "true"
      is_workload: "true"
  template:
    metadata:
      labels:
        app: cassandra-server
        can_serve: "true"
        is_workload: "true"
    spec:
      terminationGracePeriodSeconds: 15
      containers:
      - name: cassandra-server
        image: public.ecr.aws/cilantro/data-serving:server-horz
        imagePullPolicy: Always
#        # Uncomment these lines for debugging
#        command: [ "/bin/sh" ]
#        args: [ "-c", "while true; do echo hello; sleep 20;done" ]
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        - containerPort: 9160
          name: thrift
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
          privileged: true
        readinessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - /scripts/ready-probe.sh
          initialDelaySeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10 # retries
          periodSeconds: 5
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: RECORDCOUNT
            value: "100000"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP