apiVersion: batch/v1
kind: Job
metadata:
  name: ycsbclient
  labels:
    app: ycsbclient
spec:
  template:
    metadata:
      labels:
        app: ycsbclient
    spec:
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
      containers:
      - name: ycsbclient
        image: cloudsuite/data-serving:client
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        - containerPort: 9160
          name: thrift
        resources:
          limits:
            cpu: "500m"
            memory: 0.7Gi
          requests:
            cpu: "500m"
            memory: 0.7Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
          privileged: true
        lifecycle:
          preStop:
            exec:
              command: 
              - /bin/sh
              - -c
              - nodetool drain
        args: ["cassandra-server.default.svc.cluster.local"] # This is the k8s service providing load balancing
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
#          - name: CASSANDRA_SEEDS
#            value: "cassandra-0.cassandra.default.svc.cluster.local"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP