apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra-server
  name: cassandra-server
spec:
# clusterIP: None
  ports:
    - port: 7000
      name: intra-node
    - port: 7001
      name: tls-intra-node
    - port: 7199
      name: jmx
    - port: 9042
      name: cql
    - port: 9160
      name: thrift
  selector:
    app: cassandra-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-server
  labels:
    app: cassandra-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-server
  template:
    metadata:
      labels:
        app: cassandra-server
    spec:
      containers:
      - name: cassandra-server
        image: cloudsuite/data-serving:server
#        # Uncomment these lines for debugging
#        command: [ "/bin/sh" ]
#        args: [ "-c", "while true; do echo hello; sleep 20;done" ]
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        - containerPort: 9160
          name: thrift
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
          privileged: true
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: CASSANDRA_SEEDS
            value: "10.244.0.16"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP