apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-seed
  labels:
    app: cassandra-seed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-seed
  template:
    metadata:
      labels:
        app: cassandra-seed
    spec:
      containers:
      - name: cassandra-seed
        image: romilb/dataserving:latest
#        # Uncomment these lines for debugging
#        command: [ "/bin/sh" ]
#        args: [ "-c", "while true; do echo hello; sleep 20;done" ]
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
#          - name: CASSANDRA_SEEDS
#            value: "cassandra-0.cassandra.default.svc.cluster.local"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP